---
# tasks file for podman

- name: "Podman | Install from source"
  include_tasks: install.yml

- name: "Podman | Configure for rootless usage"
  include_tasks: config_rootless.yml
  when: podman_rootless == true

- name: "Podman | Configure for root usage"
  include_tasks: config_root.yml
  when: podman_rootless == false
