---
# tasks file for Hashistack

- name: "Hashistack | Node Role assignements"
  ansible.builtin.include_tasks: "01_nodes_roles.yml"

- name: "Hashistack | Commons tasks"
  ansible.builtin.include_tasks: "02_commons_tasks.yml"

- name: "Hashistack | Generate CA Cert"
  ansible.builtin.include_tasks: "03_ca_cert.yml"
  when:
  - hashistack_tls == true
  - cert_ca_tls_priv_present.stat.exists == false

- name: "Hashistack | Consul install"
  ansible.builtin.include_role:
    name: quanticware.consul.install

- name: "Hashistack | Vault install"
  ansible.builtin.include_role:
    name: quanticware.vault.install
  when: vault_node_role == 'server' or
        hashistack_install_mode == 'single'

- name: "Hashistack | Nomad install"
  ansible.builtin.include_role:
    name: quanticware.nomad.install

- name: "Hashistack | Firewall configuration"
  ansible.builtin.include_tasks: "04_firewall.yml"
  when: hashistack_firewall == true

- name: "Hashistack | Congratulations!"
  ansible.builtin.include_role:
    name: quanticware.citations.chucknorris
  vars:
    philosopher: "{{ hero_name }}"
    language: "{{ hero_lang }}"
  run_once: true
