- name: Vault KV | Check existing KV
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/{{ vault_kv_name }}/config"
    ca_path: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}"
    client_cert: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}"
    client_key: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}"
    method: GET
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    status_code:
        - 200
        - 404
  register: vault_check_kv

- name: "Enable KV Engine"
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/sys/mounts/{{ vault_kv_name }}"
    ca_path: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}"
    client_cert: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}"
    client_key: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}"
    method: POST
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    body: |
        {
          "type": "kv",
          "options": {
              "version": "2"
          }
        }
    body_format: json
    status_code:
        - 204
  when: vault_check_kv.status == 404
