---
- name: Vault token | Create Nomad token
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/auth/token/create"
    ca_path: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}"
    client_cert: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}"
    client_key: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}"
    method: POST
    headers:
        X-Vault-Token: "{{ vault_init_result.json.root_token | default(vault_root_token) }}"
    body: |
        {
          "policies": {{ vault_policies | to_json }},
          "no_parent": "true",
          "renewable": "true"
        }
    body_format: json
    status_code:
        - 200
        - 204
  register: "vault_new_token_result"

- ansible.builtin.debug:
    msg: "{{ vault_new_token_result.json.auth.client_token }}"

         # "policies": [{% for item in vault_policies_list %}"{{ item }}"{% if not loop.last %},{% endif %}{% endfor %}],
