- name: Vault Write | Delete secret
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/{{ vault_secret_path }}"
    ca_path: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}"
    client_cert: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}"
    client_key: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}"
    method: DELETE
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    status_code:
        - 204
  no_log: true
