- name: Vault | Operate | Get Status
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/sys/health"
    ca_path: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}{% endif %}"
    client_key: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}{% endif %}"
    method: GET
    headers:
        X-Vault-Token: "{{ vault_init_result.json.root_token | default(vault_root_token) }}"
    status_code:
        - 200
        - 429
        - 472
        - 473
        - 501
        - 503
  register: vault_health

- ansible.builtin.set_fact:
    vault_health_fact: "{{ vault_health.status | int }}"
- debug:
    msg: "Vault has status code: {{ vault_health.status }}"
