- name: Vault KV | Check existing KV
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/{{ vault_kv_name }}/config"
    ca_path: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}{% endif %}"
    client_key: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}{% endif %}"
    method: GET
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    status_code:
        - 200
        - 404
  register: vault_check_kv

- name: "Enable KV Engine"
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/sys/mounts/{{ vault_kv_name }}"
    ca_path: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}{% endif %}"
    client_key: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}{% endif %}"
    method: POST
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    body: |
        {
          "type": "kv",
          "options": {
              "version": "2"
          }
        }
    body_format: json
    status_code:
        - 204
  when: vault_check_kv.status == 404

- debug:
    msg: "Secret engine kv: {{ vault_kv_name }} already exists"
  when: vault_check_kv.status == 200 or vault_check_kv.status == 204
