- name: "Vault | Get secret by API (secure)"
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/{{ vault_secret_path }}"
    ca_path: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}{% endif %}"
    client_key: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}{% endif %}"
    method: GET
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    status_code:
        - 200
  register: vault_secret_return

- set_fact:
    vault_secret_value: "{{ vault_secret_return.json.data.data[vault_secret_to_get] }}"
