- name: Vault Token | Lookup a token
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/auth/token/lookup"
    ca_path: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}"
    client_cert: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}"
    client_key: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}"
    method: POST
    headers:
      X-Vault-Token: "{{ vault_root_token }}"
    body: |
      {
        "token": "{{ vault_token }}"
      }
    body_format: json
    status_code:
      - 200
  register: "vault_token_lookup"

- debug:
    msg: "{{ vault_token_lookup.json.data }}"
