- name: Vault Policies | Check policies
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/sys/policy"
    ca_path: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}{% endif %}"
    client_key: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}{% endif %}"
    method: GET
    headers:
        X-Vault-Token: "{{ vault_init_result.json.root_token | default(vault_root_token) }}"
    status_code:
        - 200
        - 404
  register: vault_policies_list

- name: Vault Policies | Create policy for {{ vault_policy_name }}
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/sys/policy/{{ vault_policy_name }}"
    ca_path: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}{% endif %}"
    client_key: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}{% endif %}"
    method: POST
    headers:
        X-Vault-Token: "{{ vault_init_result.json.root_token | default(vault_root_token) }}"
    body: |
        {
        "policy": "{{ vault_policy_rules }}"
        }
    body_format: json
    status_code:
        - 200
        - 204
  when: vault_policy_name not in vault_policies_list.json.policies

- debug:
    msg: "{{ vault_policy_name }} already exists"
  when: vault_policy_name in vault_policies_list.json.policies
