- name: Vault | Get secret by API
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/{{ vault_secret_path }}"
    ca_path: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}"
    client_cert: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}"
    client_key: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}"
    method: GET
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    status_code:
        - 200
  register: vault_secret_return

- set_fact:
    vault_secret_value: "{{ vault_secret_return.json.data.data[vault_secret_to_get] }}"
