- name: "Vault | Get secret by API (secure)"
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/{{ vault_secret_path }}"
    ca_path: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}"
    client_cert: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}"
    client_key: "{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}"
    method: GET
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    status_code:
        - 200
  register: vault_secret_return
  when: vault_unsecure == false

- set_fact:
    vault_secret_value: "{{ vault_secret_return.json.data.data[vault_secret_to_get] }}"
  when: vault_unsecure == false

- name: "Vault | Get secret by API (unsecure)"
  ansible.builtin.uri:
    url: "http://{{ vault_http_ip }}:{{ vault_http_port }}/v1/{{ vault_secret_path }}"
    method: GET
    headers:
        X-Vault-Token: "{{ vault_root_token }}"
    status_code:
        - 200
  register: vault_secret_return
  when: vault_unsecure == true

- set_fact:
    vault_secret_value: "{{ vault_secret_return.json.data.data[vault_secret_to_get] }}"
  when: vault_unsecure == true
