---
- name: Vault Operate | Write token role
  ansible.builtin.uri:
    url: "{{ vault_http_scheme }}://{{ vault_http_ip }}:{{ vault_http_port }}/v1/auth/token/roles/{{ vault_role_name }}"
    ca_path: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_cert }}{% endif %}"
    client_key: "{% if vault_tls %}{{ vault_operate_tls_host_certificate_dir }}/{{ vault_operate_tls_privatekey }}{% endif %}"
    method: POST
    headers:
        X-Vault-Token: "{{ vault_root_token | default(vault_init_result.json.root_token) }}"
    body: '{{ vault_role_rules }}'
    body_format: json
    status_code:
        - 200
        - 204
