---
# defaults file for install

# General
vault_install_mode: "{% if (ansible_play_hosts | length) == 1 %}single{% elif (ansible_play_hosts | length) > 1 %}cluster{% endif %}"
vault_node_role: "{% if vault_install_mode == 'single' %}server{% elif vault_install_mode == 'cluster' %}{% if hashistack_node_role == 'server' %}server{% else %}none{% endif %}{% endif %}"
vault_tls: true
vault_acl: true

vault_deploy_cluster_name: "{{ hashistack_cluster_name | default('default')}}"
check_online_version: true
vault_install_firewall: false

hashistack_creds_file: "{% if vault_install_mode == 'single' %}{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/hashistack.yml{% else %}{{ project_dir }}/env/group_vars/{{ vault_deploy_cluster_name }}/hashistack.yml{% endif %}"
ansible_venv_on_target_dir: "/root/hashistack_venv"

# Configuration
vault_install_dc_name: "dc1"

vault_conf_dir: "/etc/vault.d"
vault_config_file: "vault.hcl"
vault_bin_dir: "/usr/bin"

vault_install_max_lease_ttl: "768h"
vault_install_default_lease_ttl: "768h"
vault_install_disable_clustering: "false"

vault_install_ui_enabled: "true"

vault_install_disable_mlock: "true"

# Network
vault_install_http_scheme: "{% if vault_tls == true %}https{% else %}http{% endif %}"
vault_install_http_ip: "127.0.0.1"
vault_install_http_port: 8200
vault_install_cluster_port: 8201

vault_install_cluster_bridge: "brO"
vault_iface: "br0"

vault_list_node_ip:  "\
  {% set vault_list_node_ip = [] %}\
  {% for host in groups[consul_deploy_cluster_name] %}\
    {% if vault_list_node_ip.append(hostvars[host]['ansible_' + hostvars[host].vault_install_cluster_bridge].ipv4.address | default(vault_install_cluster_bridge)) %}{% endif %}\
  {% endfor %}\
  {{ vault_list_node_ip }}"

vault_bind_address: "{% if vault_install_mode == 'single' %}127.0.0.1{% else %}{{ hostvars[inventory_hostname]['ansible_'+ vault_iface | replace('-', '_')]['ipv4']['address'] }}{% endif %}"

vault_install_cluster_addr: "{{ vault_install_http_scheme }}://{{ vault_bind_address }}:{{ vault_install_cluster_port }}"
vault_install_api_addr: "{{ vault_install_http_scheme }}://{{ vault_bind_address }}:{{ vault_install_http_port }}"
vault_install_listener_tcp_address: "0.0.0.0:{{ vault_install_http_port }}"
vault_install_listener_tcp_cluster_address: "{{ vault_bind_address }}:{{ vault_install_cluster_port }}"

# Log
vault_install_log_file: "/var/log/vault/vault.log"
vault_install_log_level: "INFO"
vault_install_log_rotate_bytes: 0
vault_install_log_rotate_duration: "24h"
vault_install_log_rotate_max_files: 0

# Storage
vault_install_storage_dir: "/opt/vault/data"

# TLS
hashistack_install_tls_ca_host: localhost
hashistack_install_tls_ca_host_dir: "{% if vault_install_mode == 'single' %}{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/tls{% else %}{{ project_dir }}/env/group_vars/{{ vault_deploy_cluster_name }}/tls{% endif %}"
hashistack_install_tls_ca_pubkey: "hashistack-ca.pem"
hashistack_install_tls_ca_privatekey: "hashistack-ca-key.pem"
hashistack_install_tls_host_certificate_dir: "/etc/ssl/hashistack"
hashistack_install_tls_common_name: "hashistack"
hashistack_install_tls_check_delay: "+2w"

vault_install_tls_ca_host: localhost
vault_install_tls_ca_host_dir: "{% if vault_install_mode == 'single' %}{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/tls{% else %}{{ project_dir }}/env/group_vars/{{ vault_deploy_cluster_name }}/tls{% endif %}"
vault_install_tls_ca_pubkey: "hashistack-ca.pem"
vault_install_tls_ca_privatekey: "hashistack-ca-key.pem"
vault_install_tls_ca_provider: "ownca"

vault_install_tls_check_delay: "+2w"

vault_install_tls_host_certificate_dir: "/etc/ssl/hashistack"

vault_install_tls_cert: "{{ vault_install_dc_name }}-server-vault.pem"
vault_install_tls_privatekey: "{{ vault_install_dc_name }}-server-vault.key"

vault_install_tls_common_name: "*.{{ vault_install_dc_name }}.vault"
vault_install_tls_subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:*.{{ vault_install_dc_name }}.vault,DNS:vault.service.consul,IP:172.26.64.1,IP:172.17.0.1,IP:172.18.0.1"
# vault_install_tls_subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:*.{{ vault_install_dc_name }}.vault,IP:{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }},IP:172.26.64.1,IP:172.17.0.1,IP:172.18.0.1"

vault_install_tls_min_version: "tls12"
vault_install_tls_disable: "false"


# Consul

vault_install_consul_http_scheme: "{% if vault_tls == true %}https{% else %}http{% endif %}"
vault_install_consul_http_ip: "127.0.0.1"
vault_install_consul_http_port: "{% if vault_tls == true %}8501{% else %}8500{% endif %}"
vault_install_consul_tls_host_certificate_dir: "/etc/ssl/hashistack"
vault_install_consul_tls_ca_pubkey: "hashistack-ca.pem"
vault_install_consul_tls_cert_server: "{{ vault_install_dc_name }}-server-consul.pem"
vault_install_consul_tls_privatekey_server: "{{ vault_install_dc_name }}-server-consul.key"
vault_install_consul_tls_cert_client: "{{ vault_install_dc_name }}-client-consul.pem"
vault_install_consul_tls_privatekey_client: "{{ vault_install_dc_name }}-client-consul.key"
vault_install_consul_path: "vault"
vault_install_consul_service: "vault"
vault_install_consul_check_timeout: "5s"
vault_install_consul_disable_registration: "false"
vault_install_consul_tls_min_version: "tls12"
vault_install_consul_tls_skip_verify: "false"

# Telemetry
vault_install_telemetry_disable_hostname: "false"
vault_install_prometheus_retention_time: "24h"
vault_install_prometheus_unauthenticated_metrics_access: "true"
