- name: Hashistack Installation Single Node
  hosts: dev_single_node
  become: yes
  any_errors_fatal: true
  tasks:
  - name: Install Hashistack
    ansible.builtin.import_role:
      name: quanticware.hashistack.install
    vars:
      hero_name: Mamadoo
      hero_lang: fr
      ssh_port: 22
      hashistack_firewall: false
