repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: master
    hooks:
      - id: check-yaml
        exclude: ansible_collections/community/
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements


  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
        exclude: ansible_collections/community/
