---
- name: "Nomad ACL | Reload local facts to configure Nomad"
  ansible.builtin.setup:
    filter: ansible_local

- name: "Nomad ACL | Creation"
  block:
    - name: "Nomad ACL | Generate Bootstrap token"
      ansible.builtin.uri:
        url: "{{ nomad_install_http_scheme }}://{{ nomad_install_http_ip }}:{{ nomad_install_http_port }}/v1/acl/bootstrap"
        ca_path: "{{ nomad_install_tls_host_certificate_dir }}/{{ nomad_install_tls_ca_pubkey }}"
        client_cert: "{{ nomad_install_tls_host_certificate_dir }}/{{ nomad_install_tls_cert }}"
        client_key: "{{ nomad_install_tls_host_certificate_dir }}/{{ nomad_install_tls_privatekey }}"
        method: POST
        body_format: json
        status_code:
            - 200
      register: nomad_management_token_result

    - ansible.builtin.debug:
        msg: "{{ nomad_management_token_result.json.SecretID }}"

    - name: "Nomad ACL | Nomad management token in host_vars"
      ansible.builtin.blockinfile:
        path: "{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/hashistack.yml"
        marker: "#<!-- {mark} NOMAD MANAGEMENT TOKEN ANSIBLE MANAGED BLOCK -->"
        block: |
          nomad_management_token: "{{ nomad_management_token_result.json.SecretID }}"
        create: yes
      delegate_to: localhost
      become: no

    - ansible.builtin.set_fact:
        nomad_management_token_facts: |
          {
            "nomad_management_token": "{{ nomad_management_token_result.json.SecretID }}"
          }

    - name: "Nomad ACL | Insert Nomad management token in ansible local facts"
      ansible.builtin.copy:
        dest: /etc/ansible/facts.d/nomad_management_token.fact
        content: "{{ nomad_management_token_facts | to_nice_json }}"
        mode: "0600"
  when: ansible_local.nomad_management_token.nomad_management_token is undefined

- name: "Nomad Configuration | Enable MemoryOversubscription"
  ansible.builtin.uri:
    url: "{{ nomad_install_http_scheme }}://{{ nomad_install_http_ip }}:{{ nomad_install_http_port }}/v1/operator/scheduler/configuration"
    ca_path: "{{ nomad_install_tls_host_certificate_dir }}/{{ nomad_install_tls_ca_pubkey }}"
    client_cert: "{{ nomad_install_tls_host_certificate_dir }}/{{ nomad_install_tls_cert }}"
    client_key: "{{ nomad_install_tls_host_certificate_dir }}/{{ nomad_install_tls_privatekey }}"
    headers:
        X-Nomad-Token: "{{ nomad_management_token_result.json.SecretID | default(nomad_management_token) }}"
    method: POST
    body_format: json
    body:
      MemoryOversubscriptionEnabled: true
    return_content: yes
    status_code:
      - 200

- name: Nomad Configuration | Reload local facts
  ansible.builtin.setup:
    filter: ansible_local
