- name: "Nomad | Commons tasks | Create ansible facts directory"
  ansible.builtin.file:
    path: "/etc/ansible/facts.d"
    state: directory
    mode: '0700'
    owner: "root"
    group: "root"

- name: "Nomad | Commons tasks | Create Nomad job files directory"
  ansible.builtin.file:
    path: "{{ nomad_job_files_dir }}"
    state: directory
    mode: '0755'
    owner: "root"
    group: "root"

- name: "Nomad | Commons tasks | Install pip packages"
  ansible.builtin.pip:
    name:
    - python-nomad
    - passlib

- name: "Nomad | Commons tasks | Get GPG key"
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: "Nomad | Commons tasks | Add Hashicorp Repo for ARM64"
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  when: ansible_architecture == "aarch64"

- name: "Nomad | Commons tasks | Add Hashicorp Repo for AMD64"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  when: ansible_architecture == "x86_64"

- name: "Nomad | Commons tasks | Update APT Cache"
  ansible.builtin.apt:
    update_cache: yes

- name: "Nomad | Commons tasks | Check if TLS cert exists"
  ansible.builtin.stat:
    path: "{{ nomad_install_tls_host_certificate_dir }}/{{ nomad_install_tls_cert }}"
  register: cert_tls_present

- name: "Nomad | Commons tasks | Get information on generated certificate"
  community.crypto.x509_certificate_info:
    path: "{{ nomad_install_tls_host_certificate_dir }}/{{ nomad_install_tls_cert }}"
    valid_at:
      delay: "{{ nomad_install_tls_check_delay }}"
  register: tls_check
  when: cert_tls_present.stat.exists == true
