---
- name: "Nomad | Backup | Create backup dir"
  ansible.builtin.file:
    path: "{{ nomad_conf_dir }}/backup"
    state: directory
    mode: '0755'

- name: "Nomad | Backup | Generate backup"
  ansible.builtin.shell: "nomad operator snapshot save {{ nomad_backup_basename }}.snap"
  args:
    chdir: "{{ nomad_conf_dir }}/backup"
  environment:
    NOMAD_ADDR: "{{ nomad_http_scheme }}://{{ nomad_http_ip }}:{{ nomad_http_port }}"
    NOMAD_TOKEN: "{% if nomad_acl %}{{ nomad_management_token }}{% endif %}"
    NOMAD_CACERT: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_ca_pubkey }}{% endif %}"
    NOMAD_CLIENT_CERT: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_cert }}{% endif %}"
    NOMAD_CLIENT_KEY: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_privatekey }}{% endif %}"
