---
- name: Nomad operate | Register job in ansible pipeline
  ansible.builtin.slurp:
    src: "{{ nomad_job_file }}"
  register: job_payload

- name: Nomad operate | Submit Job (secure)
  community.general.nomad_job:
    host: localhost
    state: present
    content: "{{ job_payload['content'] | b64decode }}"
    token: "{{ nomad_management_token }}"
    use_ssl: true
    validate_certs: false
  when: nomad_unsecure == false

- name: Nomad operate | Submit Job (unsecure)
  community.general.nomad_job:
    host: localhost
    state: present
    content: "{{ job_payload['content'] | b64decode }}"
    use_ssl: false
    validate_certs: false
  when: nomad_unsecure == true
