- name: "Nomad operate | Nomad shell command find allocation ID"
  ansible.builtin.shell: nomad job allocs  -t {% raw %} '{{ range . }}{{ if eq .TaskGroup "{% endraw %}{{ nomad_operate_tasks_name }}{% raw %}" }}{{ println .ID }}{{ end }}{{ end }}' {% endraw %}{{ nomad_operate_job }}{% raw %}  | head -n 1{% endraw %}
  environment:
    NOMAD_ADDR: "{{ nomad_http_scheme }}://{{ nomad_http_ip }}:{{ nomad_http_port }}"
    NOMAD_TOKEN: "{% if nomad_acl %}{{ nomad_management_token }}{% endif %}"
    NOMAD_CLIENT_CERT: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_cert }}{% endif %}"
    NOMAD_CLIENT_KEY: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_privatekey }}{% endif %}"
    NOMAD_CACERT: "{% if nomad_tls %}{{ nomad_operate_tls_host_certificate_dir }}/{{ nomad_operate_tls_ca_pubkey }}{% endif %}"
  register: allocation_id

- debug:
    msg: "{{ allocation_id.stdout }}"
