- name: "Nomad | Operate | Requiered pip packages"
  ansible.builtin.pip:
    name: "passlib"
    state: present

- name: "Nomad | Operate | Generate password for basic auth"
  ansible.builtin.set_fact:
    traefik_nomad_basic_auth_password: "{{ lookup('ansible.builtin.password', '/dev/null') }}"
  when: traefik_nomad_basic_auth_password is not defined

- name: "Nomad | Operate | Template Traefik service for {{ fqdn }}"
  ansible.builtin.template:
    src: "traefik_service.toml.j2"
    dest: "/data/{{ fqdn_traefik }}/data/conf/{{ fqdn }}.toml"

- name: "Nomad | Operate | Nofitication by {{ delivery_method }}"
  ansible.builtin.import_role:
    name: quanticware.notification.delivery
  when: notification == true
