---
- name: "Nomad | Upgrade | Install requiered binary"
  ansible.builtin.apt:
    name: unzip
    update_cache: yes

- name: "Nomad | Upgrade | Check Nomad latest version online"
  block:
    - name: "Nomad | Upgrade | Retrieve brut list from hashicorp.com"
      ansible.builtin.uri:
        url: "https://releases.hashicorp.com/nomad/"
        return_content: yes
      register: nomad_brut_list

    - name: "Nomad | Upgrade | Extract version number"
      ansible.builtin.set_fact:
        nomad_version: '{{ nomad_brut_list.content | regex_search("nomad_[\d.]{3,}<") | regex_replace("<","") | regex_search("\d.*") }}'
  when: check_online_version == True

- name: "Nomad | Upgrade | Check Nomad installed version"
  ansible.builtin.command: nomad version
  register: nomad_installed_version

- name: "Nomad | Upgrade | Upgrade process"
  block:
    - name: "Nomad | Upgrade | Download and extract new version for ARM64"
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_arm64.zip"
        dest: "{{ nomad_path }}"
        remote_src: yes
      when: ansible_architecture == "aarch64"

    - name: "Nomad | Upgrade | Download and extract new version for ARM"
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_arm.zip"
        dest: "{{ nomad_path }}"
        remote_src: yes
      when: ansible_architecture == "armv7l"

    - name: "Nomad | Upgrade | Download and extract new version for x64"
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        dest: "{{ nomad_path }}"
        remote_src: yes
      when: ansible_architecture == "x86_64"

    - name: "Nomad | Upgrade | Restart Nomad"
      ansible.builtin.systemd:
        name: nomad
        state: restarted
  when: nomad_version is not in nomad_installed_version.stdout
