---
- name: "Consul | TLS CA Configuration"
  ansible.builtin.include_role:
    name: quanticware.certificate.create
    tasks_from: ca
  vars:
    ca_host: "{{ hashistack_install_tls_ca_host }}"
    ca_host_dir: "{{ hashistack_install_tls_ca_host_dir }}"
    ca_pubkey: "{{ hashistack_install_tls_ca_pubkey }}"
    ca_privatekey: "{{ hashistack_install_tls_ca_privatekey }}"
    host_certificate_dir: "{{ hashistack_install_tls_host_certificate_dir }}"
    common_name: "{{ hashistack_install_tls_common_name }}"
  run_once: true

- name: "Consul | Copy CA cert {{ hashistack_install_tls_ca_pubkey }} on nodes"
  ansible.builtin.copy:
    src: "{{ hashistack_install_tls_ca_host_dir }}/{{ hashistack_install_tls_ca_pubkey }}"
    dest: "{{ hashistack_install_tls_host_certificate_dir }}/{{ hashistack_install_tls_ca_pubkey }}"
