- name: "Consul | Commons tasks | Install requiered OS packages"
  ansible.builtin.apt:
    update_cache: true
    pkg: ufw

- name: "Consul | Firewall | Open ports for Consul Servers"
  community.general.ufw:
    rule: allow
    interface: "{{ consul_install_cluster_bridge }}"
    direction: "{{ item.direction }}"
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  loop:
    - { proto: "tcp", port: "8600", direction: "in" }
    - { proto: "udp", port: "8600", direction: "in" }
    - { proto: "tcp", port: "8500", direction: "in" }
    - { proto: "tcp", port: "8501", direction: "in" }
    - { proto: "tcp", port: "8502", direction: "in" }
    - { proto: "tcp", port: "8503", direction: "in" }
    - { proto: "tcp", port: "8300", direction: "in" }
    - { proto: "tcp", port: "8300", direction: "out" }
    - { proto: "tcp", port: "8301", direction: "in" }
    - { proto: "tcp", port: "8301", direction: "out" }
    - { proto: "udp", port: "8301", direction: "in" }
    - { proto: "udp", port: "8301", direction: "out" }
  when: consul_node_role == 'server' or consul_node_role == 'both'

# - name: "Consul | Firewall | Open ports for Consul Servers from HTTP and DNS"
#   community.general.ufw:
#     rule: allow
#     interface: "{{ ansible_default_ipv4.interface }}"
#     direction: "{{ item.direction }}"
#     proto: "{{ item.proto }}"
#     port: "{{ item.port }}"
#   loop:
#     - { proto: "tcp", port: "8600", direction: "in" }
#     - { proto: "udp", port: "8600", direction: "in" }
#     - { proto: "tcp", port: "8500", direction: "in" }
#     - { proto: "tcp", port: "8501", direction: "in" }
#   when: consul_node_role == 'server' or consul_node_role == 'both'

# - name: "Consul | Firewall | Open ports for Consul Servers"
#   community.general.ufw:
#     rule: allow
#     interface: "{{ ansible_default_ipv4.interface }}"
#     direction: "{{ item.direction }}"
#     proto: "{{ item.proto }}"
#     port: "{{ item.port }}"
#   loop:
#     - { proto: "tcp", port: "8302", direction: "in" }
#     - { proto: "tcp", port: "8302", direction: "out" }
#     - { proto: "udp", port: "8302", direction: "in" }
#     - { proto: "udp", port: "8302", direction: "out" }
#   when: consul_node_role == 'server' and consul_federated == true

- name: "Consul | Firewall | Open ports for Consul Clients"
  community.general.ufw:
    rule: allow
    interface: "{{ consul_install_cluster_bridge }}"
    direction: "{{ item.direction }}"
    proto: "{{ item.proto }}"
    port: "{{ item.port }}"
  loop:
    - { proto: "tcp", port: "8600", direction: "in" }
    - { proto: "udp", port: "8600", direction: "in" }
    - { proto: "tcp", port: "8500", direction: "in" }
    - { proto: "tcp", port: "8501", direction: "in" }
    - { proto: "tcp", port: "8502", direction: "in" }
    - { proto: "tcp", port: "8503", direction: "in" }
    - { proto: "tcp", port: "8301", direction: "in" }
    - { proto: "tcp", port: "8301", direction: "out" }
    - { proto: "udp", port: "8301", direction: "in" }
    - { proto: "udp", port: "8301", direction: "out" }
  when: consul_node_role == 'client'
