---
# tasks file for install

- name: "Consul | Commons tasks"
  ansible.builtin.include_tasks: "commons_tasks.yml"

- name: "Consul | TLS Configuration"
  ansible.builtin.import_role:
    name: quanticware.certificate.create
    tasks_from: client
  vars:
    host_certificate_dir: "{{ consul_install_tls_host_certificate_dir }}"
    ca_host_dir: "{{ consul_install_tls_ca_host_dir }}"
    ca_pubkey: "{{ consul_install_tls_ca_pubkey }}"
    ca_privatekey: "{{ consul_install_tls_ca_privatekey }}"
    ca_provider: "{{ consul_install_tls_ca_provider }}"
    ca_host: "{{ consul_install_tls_ca_host }}"
    cert: "{{ consul_install_tls_cert }}"
    client_privatekey: "{{ consul_install_tls_privatekey }}"
    common_name: "{{ consul_install_tls_common_name }}"
    subject_alt_name: "{{ consul_install_tls_subject_alt_name }}"
  when: cert_tls_present.stat.exists == false or
        (cert_tls_present.stat.exists == true and tls_check.valid_at.delay == false)

- name: "Consul | Install"
  ansible.builtin.include_tasks: "install.yml"

- name: "Consul | ACL Configuration"
  ansible.builtin.include_tasks: "acl.yml"
