- name:  "{{ app_name }} | Check stats of job file"
  ansible.builtin.stat:
    path: "{{ nomad_job_files_dir }}/{{ job_name }}.hcl"
  register: job

- name: "{{ app_name }} | Write secret for app credentials"
  ansible.builtin.import_role:
    name: quanticware.vault.operate
  vars:
    role_action: write
    vault_secret_path: "apps/data/{{ fqdn }}"
    vault_secret:
      data:
        vault_token: "{{ vault_token }}"
        vault_root_token: "{{ vault_root_token }}"
  when:
  - vault_state == "write"
  - vault_token_renew_self == false

- name: "{{ app_name }} | Write secret for app credentials"
  ansible.builtin.import_role:
    name: quanticware.vault.operate
  vars:
    role_action: write
    vault_secret_path: "apps/data/{{ fqdn }}"
    vault_secret:
      data:
        vault_token: "{{ vault_token }}"
  when:
  - vault_state == "write"
  - vault_token_renew_self == true
