---
#tasks file for ansible-rundeck

- name: "{{ app_name }} | Checks if mandatory variables are sets"
  ansible.builtin.include_tasks: checks.yml

- name: "{{ app_name }} | Deploy with {{ install_method }}"
  ansible.builtin.import_role:
    name: quanticware.deploy.nomad
  when: install_method == "nomad"
