- name: "Docker Install | Mandatories packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip
    - lsb-release

- name: "Docker Install | Add repository"
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: "https://download.docker.com/linux/{{ ansible_distribution | lower }}"
    signed_by: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    suites: ["{{ ansible_distribution_release | lower }}"]
    components: [stable]
    state: present
    enabled: yes
  register: docker_add_repo

- name: "Docker Install | Apt Update"
  ansible.builtin.apt:
    update_cache: yes
  when: docker_add_repo.changed

- name: "Docker Install | Uninstall OS defaults Docker packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-engine
    - docker.io
    - containerd
    - runc

- name: "Docker Install | Install Docker packages from official repository"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose

- name: "Docker Install | Pip packages"
  ansible.builtin.pip:
    name: "docker"
    state: present

- name: "Docker Install | Add user to docker group"
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: yes

- name: "Docker Install | Log into private registry and force re-authorization"
  community.docker.docker_login:
    registry_url: "{{ docker_private_registry_url }}"
    username: "{{ docker_private_registry_username }}"
    password: "{{ docker_private_registry_password }}"
    reauthorize: true
  when: docker_private_registry_state == true

- name: "Docker Install | Systemd start and enable"
  ansible.builtin.systemd:
    state: started
    name: docker
    enabled: yes
