---
- name: "Docker Install | Install"
  ansible.builtin.include_tasks: install.yml

- name: "Docker Install | Configure TLS"
  ansible.builtin.include_tasks: tls.yml
  when: docker_tls_configuration == true

- name: "Docker Install | Firewall"
  ansible.builtin.include_tasks: firewall.yml
  when: firewall == true
