---
# defaults file for install

# General
nomad_install_mode: "single_node"

nomad_install_http_scheme: "https"
nomad_install_http_ip: "127.0.0.1"
nomad_install_http_port: 4646
nomad_install_node_name: "{{ inventory_hostname_short }}"
nomad_install_region: "global"

check_online_version: true
nomad_config_dir: "/etc/nomad.d"
nomad_config_file: "nomad.hcl"
nomad_bin_dir: "/usr/bin"
nomad_install_data_dir: "/opt/nomad"
nomad_job_files_dir: "/var/tmp/hashistack/nomad"

nomad_install_dc_name: "dc1"

nomad_install_disable_update_check: "false"

nomad_install_leave_on_terminate: true
nomad_install_leave_on_interrupt: true

# Network
nomad_install_bridge_list:
- { name: "br0", ip_range: "172.18.0.1/16" }

# Log
nomad_install_debug: "false"
nomad_install_log_file: "/var/log/nomad/nomad.log"
nomad_install_log_level: "INFO"
nomad_install_log_rotate_bytes: 0
nomad_install_log_rotate_duration: "24h"
nomad_install_log_rotate_max_files: 0

# Plugins
nomad_docker_driver: true
nomad_podman_driver: false
nomad_raw_exec_driver: false
podman_rootless: true

# Docker
docker_tls_configuration: false

nomad_install_docker_client_dc_name: "dc1"

nomad_install_docker_tcp_listen_address: "127.0.0.1"
nomad_install_docker_tcp_listen_port: 2376

nomad_install_docker_client_tls_host_certificate_dir: "/etc/ssl/docker"
nomad_install_docker_client_tls_cert: "{{ nomad_install_docker_client_dc_name }}-client-docker.pem"
nomad_install_docker_client_tls_privatekey: "{{ nomad_install_docker_client_dc_name }}-client-docker.key"
nomad_install_docker_client_tls_ca_pubkey: "docker-ca.pem"

nomad_install_docker_client_allow_caps:
- audit_write
- chown
- dac_override
- fowner
- fsetid
- kill
- mknod
- net_bind_service
- setfcap
- setgid
- setpcap
- setuid
- sys_chroot
- sys_ptrace
- sys_admin

nomad_install_docker_private_registry_state: false
nomad_install_docker_private_registry_url: ""
nomad_install_docker_private_registry_username: ""
nomad_install_docker_private_registry_password: ""
nomad_install_docker_private_registry_config: "{{ nomad_config_dir }}/docker_config.json"

# Addresses
nomad_iface: "{{ ansible_default_ipv4.interface }}"
nomad_bind_address: "{% if nomad_install_mode == 'single_node' %}127.0.0.1{% else %}{{ hostvars[inventory_hostname]['ansible_'+ nomad_iface | replace('-', '_')]['ipv4']['address'] }}{% endif %}"
nomad_install_bind_addr: "0.0.0.0"

nomad_install_advertise_http: "{% if nomad_install_mode == 'single_node' %}127.0.0.1{% else %}{{ hostvars[inventory_hostname]['ansible_'+ nomad_iface | replace('-', '_')]['ipv4']['address'] }}{% endif %}:{{ nomad_install_port_http }}"
nomad_install_advertise_rpc: "{% if nomad_install_mode == 'single_node' %}127.0.0.1{% else %}{{ hostvars[inventory_hostname]['ansible_'+ nomad_iface | replace('-', '_')]['ipv4']['address'] }}{% endif %}:{{ nomad_install_port_rpc }}"
nomad_install_advertise_serf: "{% if nomad_install_mode == 'single_node' %}127.0.0.1{% else %}{{ hostvars[inventory_hostname]['ansible_'+ nomad_iface | replace('-', '_')]['ipv4']['address'] }}{% endif %}:{{ nomad_install_port_serf }}"

nomad_install_port_http: 4646
nomad_install_port_rpc: 4647
nomad_install_port_serf: 4648

# Server
nomad_install_server_enabled: "true"

nomad_install_server_bootstrap_expect: 1

nomad_install_server_rejoin_after_leave: "false"

nomad_install_server_enabled_schedulers:
- service
- batch
- system

nomad_install_server_num_schedulers: 2

nomad_install_server_node_gc_threshold: "24h"
nomad_install_server_eval_gc_threshold: "1h"
nomad_install_server_job_gc_threshold: "4h"
nomad_install_server_deployment_gc_threshold: "1h"

#nomad_install_server_encrypt: ""

nomad_install_server_raft_protocol: 3

# Client
nomad_install_client_enabled: "true"

#nomad_install_client_node_class: ""
nomad_install_client_no_host_uuid: "false"
nomad_install_client_max_kill_timeout: "30s"

nomad_install_client_host_network_list:
- { name: "public", interface: "{{ ansible_default_ipv4.interface }}" }
- { name: "private", interface: "{{ nomad_install_bridge_list | map(attribute='name') | first }}" }


nomad_install_client_servers:
- 127.0.0.1:4647

nomad_install_client_server_join:
- 127.0.0.1

nomad_install_client_server_join_retry_max: 3
nomad_install_client_server_join_retry_interval: "15s"

nomad_install_client_drain_on_shutdown_deadline: "1m"
nomad_install_client_drain_on_shutdown_force: "true"
nomad_install_client_drain_on_shutdown_ignore_system_jobs: "true"

nomad_install_client_network_speed: 0
nomad_install_client_cpu_total_compute: 0

nomad_install_client_gc_interval: "1m"
nomad_install_client_gc_disk_usage_threshold: 80
nomad_install_client_gc_inode_usage_threshold: 70
nomad_install_client_gc_parallel_destroys: 2

nomad_install_client_reserved_cpu: 0
nomad_install_client_reserved_memory: 0
nomad_install_client_reserved_disk: 0

# TLS
nomad_install_tls_http: "true"
nomad_install_tls_rpc: "true"

nomad_install_tls_ca_host: localhost
nomad_install_tls_ca_host_dir: "{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/tls"
nomad_install_tls_ca_pubkey: "hashistack-ca.pem"
nomad_install_tls_ca_privatekey: "hashistack-ca-key.pem"
nomad_install_tls_ca_provider: "ownca"

nomad_install_tls_check_delay: "+2w"

nomad_install_tls_host_certificate_dir: "/etc/ssl/hashistack"

nomad_install_tls_cert: "{{ nomad_install_dc_name }}-server-nomad.pem"
nomad_install_tls_privatekey: "{{ nomad_install_dc_name }}-server-nomad.key"

nomad_install_tls_common_name: "*.{{ nomad_install_dc_name }}.nomad"
nomad_install_tls_subject_alt_name: "DNS:localhost,IP:127.0.0.1,DNS:server.global.nomad,DNS:server.{{ nomad_install_dc_name }}.nomad"

nomad_install_tls_rpc_upgrade_mode: "false"
nomad_install_tls_verify_server_hostname: "true"
nomad_install_tls_verify_https_client: "false"

# ACL
nomad_install_acl_enabled: "true"
nomad_install_acl_token_ttl: "30s"
nomad_install_acl_policy_ttl: "30s"


# Consul
nomad_install_backend_consul_http_scheme: "https"
nomad_install_backend_consul_http_ip: "127.0.0.1"
nomad_install_backend_consul_http_port: 8501
nomad_install_backend_consul_grpc_port: 8503
nomad_install_backend_consul_ssl: "true"

nomad_install_backend_consul_tls_host_certificate_dir: "/etc/ssl/hashistack"
nomad_install_backend_consul_tls_ca_pubkey: "hashistack-ca.pem"
nomad_install_backend_consul_tls_cert: "{{ nomad_install_dc_name }}-server-consul.pem"
nomad_install_backend_consul_tls_privatekey: "{{ nomad_install_dc_name }}-server-consul.key"

nomad_install_backend_consul_server_service_name: "nomad-servers"
nomad_install_backend_consul_client_service_name: "nomad-clients"

nomad_install_backend_consul_auto_advertise: "true"

nomad_install_backend_consul_server_auto_join: "true"
nomad_install_backend_consul_client_auto_join: "true"

nomad_install_consul_service_address: 172.17.0.1

# Vault
nomad_install_backend_vault_http_scheme: "https"
nomad_install_backend_vault_http_ip: "127.0.0.1"
nomad_install_backend_vault_http_port: 8200

nomad_install_vault_create_from_role: "nomad-cluster"
nomad_install_vault_tls_skip_verify: "false"

nomad_install_vault_tls_host_certificate_dir: "/etc/ssl/hashistack"
nomad_install_vault_consul_tls_ca_pubkey: "hashistack-ca.pem"
nomad_install_vault_tls_cert: "{{ nomad_install_dc_name }}-server-vault.pem"
nomad_install_vault_tls_privatekey: "{{ nomad_install_dc_name }}-server-vault.key"

# Docker
nomad_install_docker_allow_privileged: "false"
nomad_install_docker_volume_enable: "true"
nomad_install_docker_gc_image: "true"
nomad_install_docker_gc_image_delay: "1h"
nomad_install_docker_gc_container: "true"
nomad_install_docker_gc_dangling_containers_enabled: "true"
nomad_install_docker_gc_dangling_containers_dry_run: "false"
nomad_install_docker_gc_dangling_containers_period: "5m"
nomad_install_docker_gc_dangling_containers_creation_grace: "5m"

# Podman
nomad_install_podman_socket_path: "unix://run/podman/podman.sock"
nomad_install_podman_volume_enabled: "true"

# Telemetry
nomad_install_telemetry_disable_hostname: "false"
nomad_install_telemetry_collection_interval: "5s"
nomad_install_telemetry_use_node_name: "false"
nomad_install_telemetry_publish_allocation_metrics: "true"
nomad_install_telemetry_publish_node_metrics: "true"
nomad_install_telemetry_filter_default: "true"
# nomad_install_telemetry_prefix_filter:
nomad_install_telemetry_disable_dispatched_job_summary_metrics: "false"
# nomad_install_telemetry_statsite_address: ""
# nomad_install_telemetry_statsd_address: ""
# nomad_install_telemetry_datadog_address: ""
# nomad_install_telemetry_datadog_tags:
nomad_install_telemetry_prometheus_metrics: "true"
#nomad_install_telemetry_circonus_api_token: ""
nomad_install_telemetry_circonus_api_app: "nomad"
nomad_install_telemetry_circonus_api_url: "https://api.circonus.com/v2"
nomad_install_telemetry_circonus_submission_interval: "10s"
# nomad_install_telemetry_circonus_submission_url: ""
# nomad_install_telemetry_circonus_check_id: ""
nomad_install_telemetry_circonus_check_force_metric_activation: "false"
# nomad_install_telemetry_circonus_check_instance_id: ""
# nomad_install_telemetry_circonus_check_search_tag: ""
# nomad_install_telemetry_circonus_check_display_name: ""
# nomad_install_telemetry_circonus_check_tags: ""
# nomad_install_telemetry_circonus_broker_id: ""
# nomad_install_telemetry_circonus_broker_select_tag: ""

# Autopilot
nomad_install_autopilot_cleanup_dead_servers: "true"
nomad_install_autopilot_last_contact_threshold: "200ms"
nomad_install_autopilot_max_trailing_logs: 250
nomad_install_autopilot_server_stabilization_time: "10s"

# UI
nomad_install_ui_enabled: "true"
nomad_install_ui_content_security_policy_connect_src: "*"
nomad_install_ui_content_security_policy_default_src: "'none'"
nomad_install_ui_content_security_policy_form_action: "'none'"
nomad_install_ui_content_security_policy_frame_ancestors: "'none'"
nomad_install_ui_content_security_policy_img_src: ""
nomad_install_ui_content_security_policy_script_src: "'self'"
nomad_install_ui_content_security_policy_style_src: ""

nomad_install_ui_consul_ui_url: "https://127.0.0.1:8501/ui"
nomad_install_ui_vault_ui_url: "https://127.0.0.1:8200/ui"

nomad_install_ui_label_text: "{{ inventory_hostname }}"
nomad_install_ui_label_background_color: "blue"
nomad_install_ui_label_text_color: "white"
