---
# defaults file for hashistack

app_name: hashistack
role_user: root

# hashistack info
check_online_version: False
hashistack_definitions_files_dir: "/var/tmp/hashistack"
hashistack_backup_retention: "3d"

# CONSUL
consul_http_scheme: "{% if vault_unsecure == false %}https{% else %}http{% endif %}"
consul_http_ip: "127.0.0.1"
consul_http_port: "{% if vault_unsecure == false %}8501{% else %}8500{% endif %}"
consul_unsecure: false
consul_operate_dc_name: "dc1"

consul_conf_dir: "/etc/consul.d"
consul_workdir: "/opt/consul"
consul_backup_basename: "consul_{{ inventory_hostname | replace('.', '_') }}_{{ ansible_date_time.date }}-{{ ansible_date_time.time | replace(':', '-') }}"

consul_operate_tls_ca_pubkey: "hashistack-ca.pem"
consul_operate_tls_host_certificate_dir: "/etc/ssl/hashistack"
consul_operate_tls_cert: "{{ consul_operate_dc_name }}-server-consul.pem"
consul_operate_tls_privatekey: "{{ consul_operate_dc_name }}-server-consul.key"

#consul_version: 1.12.3
consul_upgrade: True

# VAULT
vault_http_scheme: "{% if vault_unsecure == false %}https{% else %}http{% endif %}"
vault_http_ip: "127.0.0.1"
vault_http_port: 8200
vault_unsecure: false
vault_consul_backend: true
vault_operate_dc_name: "dc1"

vault_conf_dir: "/etc/vault.d"
vault_workdir: "/opt/vault"
vault_backup_basename: "vault_{{ inventory_hostname | replace('.', '_') }}_{{ ansible_date_time.date }}-{{ ansible_date_time.time | replace(':', '-') }}"

vault_operate_tls_host_certificate_dir: "/etc/ssl/hashistack"

vault_consul_backend_http_scheme: "https"
vault_consul_backend_http_ip: "127.0.0.1"
vault_consul_backend_http_port: "{% if vault_unsecure == false %}8501{% else %}8500{% endif %}"
vault_consul_backend_tls_ca_pubkey: "hashistack-ca.pem"
vault_consul_backend_tls_cert: "{{ consul_operate_tls_cert }}"
vault_consul_backend_tls_privatekey: "{{ consul_operate_tls_privatekey }}"

#vault_version: 1.11.1
vault_upgrade: True

# NOMAD
nomad_http_scheme: "{% if nomad_unsecure == false %}https{% else %}http{% endif %}"
nomad_http_ip: "127.0.0.1"
nomad_http_port: 4646
nomad_job_files_dir: "{{ hashistack_definitions_files_dir }}/nomad"
nomad_job_file: "{{ nomad_job_files_dir }}/{{ job_name }}.hcl"
nomad_job_name: "{{ fqdn }}"
nomad_unsecure: false
nomad_operate_dc_name: "dc1"

nomad_conf_dir: "/etc/nomad.d"
nomad_workdir: "/opt/nomad"
nomad_backup_basename: "nomad_{{ inventory_hostname | replace('.', '_') }}_{{ ansible_date_time.date }}-{{ ansible_date_time.time | replace(':', '-') }}"

nomad_operate_tls_host_certificate_dir: "/etc/ssl/hashistack"
nomad_operate_tls_ca_pubkey: "hashistack-ca.pem"
nomad_operate_tls_cert: "{{ nomad_operate_dc_name }}-server-nomad.pem"
nomad_operate_tls_privatekey: "{{ nomad_operate_dc_name }}-server-nomad.key"

#nomad_version: 1.3.2
nomad_upgrade: True

binary_path: "/usr/bin"
consul_path: "{{ binary_path }}"
vault_path: "{{ binary_path }}"
nomad_path: "{{ binary_path }}"

# Backup
backup_cron: "hourly" # "annually","daily","hourly","monthly","reboot","weekly","yearly"
datas_dir: "/data/{{ fqdn }}/data"
backup_customs_tasks_state: false

restic_keep_daily: 7
restic_keep_weekly: 10
restic_keep_monthly: 24

database_backup: false
database_type: "none"
database_host: "127.0.0.1"
database_backup_retention: "30d"

playbook_template: "{{ ressources  }}/ansible/playbook_backup.yml.j2"

# MinIO
minio_user: "{{ fqdn }}"

# Restic
restic_includes:
- /data/{{ fqdn }}/data
- /data/{{ fqdn }}/backup

# restic_excludes:

# Consul
consul_operation: false

# Vault
vault_secret: "apps/data/{{ fqdn }}"
