---
# tasks file for backup

- name: "Vault Unseal | Install pip module"
  ansible.builtin.pip:
    name: "{{ item }}"
  loop:
  - ansible

- name: "Vault Unseal | Copy auto-unseal playbook"
  ansible.builtin.template:
    src: "vault_unseal.yml.j2"
    dest: "/root/vault_unseal.yml"
    mode: "0644"

- name: "Vault Unseal | Copy service systemd file"
  copy:
    src: vault-unseal.service
    dest: /lib/systemd/system/vault-unseal.service
    owner: root
    group: root
    mode: '0644'

- name: "Vault Unseal | Add vault-unseal.service to Wants of Vault systemd unit file"
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/vault.service
    insertafter: 'Requires=network-online.target'
    line: 'Wants=vault-unseal.service'

- name: "Vault Unseal | Check if Nomad binary exists"
  ansible.builtin.stat:
    path: "{{ nomad_binary_path }}"
  register: nomad_binary

- name: "Vault Unseal | Add vault-unseal.service wait to Nomad the systemd unit file"
  ansible.builtin.lineinfile:
    path: /lib/systemd/system/nomad.service
    insertafter: 'After=consul.service'
    line: 'After=vault-unseal.service'
  when: nomad_binary.stat.exists == true

- name: "Vault Unseal | Register systemd service"
  ansible.builtin.systemd:
    name: vault-unseal.service
    enabled: true
    daemon_reload: true
