- name: "CNI | Create directory for bin"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
    owner: "{{ role_user }}"
    group: "{{ role_user }}"
  loop:
  - /opt/cni/bin
  - /opt/cni/config
  when: cni_install.stat.exists == false

- name: "CNI | Retreive GitHub latest version"
  ansible.builtin.uri:
    url: https://api.github.com/repos/containernetworking/plugins/releases/latest
    body_format: json
    return_content: yes
  register: tag

- ansible.builtin.set_fact:
    cni_version: "{{ tag.json.tag_name | replace('v','') }}"

- ansible.builtin.debug:
    msg:
    - "CNI: version {{ cni_version }}"

- name: "CNI | Unarchive plugin CNI for {{ go_arch | upper }}"
  ansible.builtin.unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/{{ tag.json.tag_name }}/cni-plugins-linux-{{ go_arch }}-{{ tag.json.tag_name }}.tgz
    dest: /opt/cni/bin
    remote_src: yes

- name: "CNI | Add to sysctl"
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
   - { name: "net.bridge.bridge-nf-call-arptables", value: "1" }
   - { name: "net.bridge.bridge-nf-call-ip6tables", value: "1" }
   - { name: "net.bridge.bridge-nf-call-iptables", value: "1" }
