---
# defaults file for hashistack
app_name: hashistack
role_user: root
hero_name: "Armon Dadgar"
hero_lang: "en"

# Hashistack
hashistack_access: "cloud" # cloud | onpremise
check_online_version: true
# consul_version: 1.15.3
# vault_version: 1.13.3
# nomad_version: 1.5.6

hashistack_deploy_dc_name: "dc1"

# TLS
hashistack_install_tls_ca_host: localhost
hashistack_install_tls_ca_host_dir: "{{ project_dir }}/env/host_vars/{{ hashistack_deploy_dc_name }}/tls"
hashistack_install_tls_ca_pubkey: "hashistack-ca.pem"
hashistack_install_tls_ca_privatekey: "hashistack-ca-key.pem"
hashistack_install_tls_host_certificate_dir: "/etc/ssl/hashistack"
hashistack_install_tls_common_name: "hashistack"
hashistack_install_tls_check_delay: "+2w"

# Nomad
nomad_docker_driver: true
nomad_podman_driver: false

# Firewall
hashistack_firewall: true
ssh_port: 22
