---
# defaults file for backup

app_name: auto-unseal
role_user: root
fqdn: "vault"

# Vault info
vault_install_http_scheme: "https"
vault_install_http_ip: "127.0.0.1"
vault_install_http_port: 8200

vault_install_dc_name: "dc1"

vault_install_tls_ca_pubkey: "hashistack-ca.pem"
vault_install_tls_cert: "{{ vault_install_dc_name }}-server-vault.pem"
vault_install_tls_privatekey: "{{ vault_install_dc_name }}-server-vault.key"
