---
# defaults file for backup

app_name: auto-unseal
role_user: root
fqdn: "vault"
ansible_venv_on_target_dir: "/root/hashistack_venv"

# Vault info
vault_install_http_scheme: "{% if vault_tls == true %}https{% else %}http{% endif %}"
vault_install_http_ip: "127.0.0.1"
vault_install_http_port: 8200

vault_install_dc_name: "dc1"

vault_install_tls_host_certificate_dir: "/etc/ssl/hashistack"
vault_install_tls_ca_pubkey: "hashistack-ca.pem"
vault_install_tls_cert: "{{ vault_install_dc_name }}-server-vault.pem"
vault_install_tls_privatekey: "{{ vault_install_dc_name }}-server-vault.key"

# Nomad
nomad_binary_path: /usr/bin/nomad
