- name: "Vault | Consul ACL | Reload local facts"
  ansible.builtin.setup:
    filter: ansible_local

- name: "Vault | Consul ACL | Create Consul policy for Vault"
  ansible.builtin.import_role:
    name: "quanticware.consul.operate"
    tasks_from: create_policy
  vars:
    consul_policy_name: vault-service
    consul_policy_rules: 'key_prefix \"vault/\" {\n \"policy\" = \"write\"\n }\n \n service \"vault\" {\n \"policy\" = \"write\"\n }\n \n agent_prefix \"\" {\n \"policy\" = \"read\"\n }\n \n session_prefix \"\" {\n \"policy\" = \"write\"\n }\n'

- name: "Vault | Consul Token |  Create Consul token for Vault"
  ansible.builtin.import_role:
    name: "quanticware.consul.operate"
    tasks_from: create_token
  vars:
    consul_token_name: "vault"
    consul_policy_name: "vault-service"

- name: "Vault | Consul ACL | Reload local facts"
  ansible.builtin.setup:
    filter: ansible_local
