- name: "Consul Token | Get tokens list"
  ansible.builtin.uri:
    url: "{{ consul_http_scheme }}://{{ consul_http_ip }}:{{ consul_http_port }}/v1/acl/tokens"
    ca_path: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_ca_pubkey }}"
    client_cert: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_cert }}"
    client_key: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_privatekey }}"
    method: GET
    headers:
      X-Consul-Token: "{{ consul_acl_master_token | default(ansible_local.consul_acl_master_token.consul_acl_master_token) }}"
    status_code:
        - 200
        - 404
    return_content: yes
  register: consul_tokens_list_raw

- ansible.builtin.set_fact:
    consul_tokens_list: "{{ consul_tokens_list_raw.json | community.general.json_query('[*].Description') | string }}"

- name: "Consul Token | {{ consul_token_name }} token creation and insert in ansible local facts"
  block:
    - name: Consul Token | Create token for {{ consul_token_name }} Consul access
      ansible.builtin.uri:
        url: "{{ consul_http_scheme }}://{{ consul_http_ip }}:{{ consul_http_port }}/v1/acl/token"
        ca_path: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_ca_pubkey }}"
        client_cert: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_cert }}"
        client_key: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_privatekey }}"
        method: PUT
        headers:
          X-Consul-Token: "{{ consul_acl_master_token | default(ansible_local.consul_acl_master_token.consul_acl_master_token) }}"
        body: |
            {
              "Description": "{{ consul_token_name }}",
              "Policies": [
                {
                  "Name": "{{ consul_policy_name | lower }}"
                }
              ]
            }
        body_format: json
        status_code:
            - 200
      register: consul_new_token_name

    - name: "Consul Token | {{ consul_token_name }} token in host_vars"
      ansible.builtin.blockinfile:
        path: "{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/hashistack.yml"
        marker: "#<!-- {mark} CONSUL {{ consul_token_name | upper }} TOKEN ANSIBLE MANAGED BLOCK -->"
        block: |
          consul_{{ consul_token_name }}_token: "{{ consul_new_token_name.json.SecretID }}"
        create: yes
      delegate_to: localhost
      become: no

    - ansible.builtin.set_fact:
        consul_new_token_facts: |
          {
            "consul_{{ consul_token_name }}_token": "{{ consul_new_token_name.json.SecretID }}"
          }

    - name: Consul Token | Insert Consul facts in ansible local facts
      ansible.builtin.copy:
        dest: /etc/ansible/facts.d/consul_{{ consul_token_name }}_token.fact
        content: "{{ consul_new_token_facts | to_nice_json }}"
        mode: "0600"
  when: 'consul_token_name not in consul_tokens_list'

- name: "Consul Token | Reload local facts"
  ansible.builtin.setup:
    filter: ansible_local
