- name: "Consul Operate | DNS Resolution | Create default directory"
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: 0755

- name: "Consul Operate | DNS Resolution | Copy config"
  ansible.builtin.copy:
    content: |
      [Resolve]
      DNS=127.0.0.1:8600
      DNSSEC=no
      DNSOverTLS=no
      Domains=~consul
      Cache=no
      DNSStubListenerExtra=172.17.0.1
    dest: /etc/systemd/resolved.conf.d/consul.conf
    mode: 0644

- name: "Consul Operate | DNS Resolution | Restart service"
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true
    name: systemd-resolved

- block:
    - name: "Consul Operate | DNS Resolution | Create Consul policy"
      ansible.builtin.include_role:
        name: "quanticware.consul.operate"
        tasks_from: policy_create
      vars:
        consul_policy_name: dns-queries
        consul_policy_rules: 'node_prefix \"\" {\n policy = \"read\"\n }\n \n service_prefix \"\" {\n policy = \"read\"\n }\n'
      run_once: true

    - name: "Consul Operate | DNS Resolution | Update anonymous token to accept DNS queries"
      ansible.builtin.uri:
        url: "{{ consul_http_scheme }}://{{ consul_http_ip }}:{{ consul_http_port }}/v1/acl/token/00000000-0000-0000-0000-000000000002"
        ca_path: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_ca_pubkey }}{% endif %}"
        client_cert: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_cert }}{% endif %}"
        client_key: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_privatekey }}{% endif %}"
        method: PUT
        headers:
          X-Consul-Token: "{% if consul_acl %}{{ consul_global_management_token | default(ansible_local.consul_global_management_token.consul_global_management_token) }}{% endif %}"
        body: |
            {
              "Policies": [
                {
                "Name": "dns-queries"
                }
              ],
              "Local": false
            }
        body_format: json
        status_code:
            - 200
      run_once: true
  when: consul_acl == true
