- name: "Consul Operate | Deregister service {{ consul_service_name }}"
  ansible.builtin.uri:
    url: "{{ consul_http_scheme }}://{{ consul_http_ip }}:{{ consul_http_port }}/v1/agent/service/deregister/{{ consul_service_name }}"
    ca_path: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_ca_pubkey }}{% endif %}"
    client_cert: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_cert }}{% endif %}"
    client_key: "{% if consul_tls %}{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_privatekey }}{% endif %}"
    method: PUT
    headers:
      X-Consul-Token: "{% if consul_acl %}{{ consul_global_management_token | default(consul_master_token) }}"
    status_code:
        - 200
