- name: "Consul Operate | Register service {{ consul_service_name }}"
  ansible.builtin.uri:
    url: "{{ consul_http_scheme }}://{{ consul_http_ip }}:{{ consul_http_port }}/v1/agent/service/register"
    ca_path: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_ca_pubkey }}"
    client_cert: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_cert }}"
    client_key: "{{ consul_operate_tls_host_certificate_dir }}/{{ consul_operate_tls_privatekey }}"
    method: PUT
    body_format: json
    body: "{{ lookup('ansible.builtin.template','service_register.json.j2') }}"
    headers:
      X-Consul-Token: "{{ consul_acl_master_token | default(consul_master_token) }}"
    status_code:
        - 200
