---
- name: "Consul | Upgrade | Install requiered binary"
  ansible.builtin.apt:
    name: unzip
    update_cache: yes

- name: "Consul | Upgrade | Check Consul latest version online"
  block:
    - name: "Consul | Upgrade | Retrieve brut list from hashicorp.com"
      ansible.builtin.uri:
        url: "https://releases.hashicorp.com/consul/"
        return_content: yes
      register: consul_brut_list

    - name: "Consul | Upgrade | Extract version number"
      ansible.builtin.set_fact:
        consul_version: '{{ consul_brut_list.content | regex_search("consul_[\d.]{3,}<") | regex_replace("<","") | regex_search("\d.*") }}'
  when: check_online_version == True

- name: "Consul | Upgrade | Check Consul installed version"
  ansible.builtin.command: consul version
  register: consul_installed_version

- name: "Consul | Upgrade | Upgrade process"
  block:
    - name: "Consul | Upgrade | Download and extract new version for ARM64"
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_arm64.zip"
        dest: "{{ consul_path }}"
        remote_src: yes
      when: ansible_architecture == "aarch64"

    - name: "Consul | Upgrade | Download and extract new version for ARM"
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_arm.zip"
        dest: "{{ consul_path }}"
        remote_src: yes
      when: ansible_architecture == "armv7l"

    - name: "Consul | Upgrade | Download and extract new version for x64"
      ansible.builtin.unarchive:
        src: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: "{{ consul_path }}"
        remote_src: yes
      when: ansible_architecture == "x86_64"

    - name: "Consul | Upgrade | Restart Consul"
      ansible.builtin.systemd_service:
        name: consul
        state: restarted
  when: consul_version is not in consul_installed_version.stdout
