- name: "Hashistack | Commons tasks | Create ansible facts directory"
  ansible.builtin.file:
    path: "/etc/ansible/facts.d"
    state: directory
    mode: '0700'
    owner: "root"
    group: "root"

- name: "Hashistack | Commons tasks | Install python pip"
  ansible.builtin.apt:
    update_cache: true
    pkg:
    - python3-pip
    - jq

- name: "Hashistack | Commons tasks | Install pip packages"
  ansible.builtin.pip:
    name:
    - ansible
    - passlib
    - python-nomad
    - python-consul

- name: "Hashistack | Commons tasks | Get GPG key"
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: "Hashistack | Commons tasks | Add Hashicorp Repo for ARM64"
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  when: ansible_architecture == "aarch64"

- name: "Hashistack | Commons tasks | Add Hashicorp Repo for AMD64"
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
  when: ansible_architecture == "x86_64"

- name: "Hashistack | Commons tasks | Update APT Cache"
  ansible.builtin.apt:
    update_cache: yes

- name: "Hashistack | Commons tasks | Check if TLS CA exists"
  ansible.builtin.stat:
    path: "{{ hashistack_install_tls_ca_host_dir }}/{{ hashistack_install_tls_ca_privatekey }}"
  register: cert_ca_tls_priv_present
  delegate_to: localhost

- name: "Hashistack | Commons tasks | Add all hosts running this playbook to the group hashistack"
  ansible.builtin.add_host:
    name: '{{ item }}'
    groups: hashistack
  loop: "{{ hashsitack_nodes }}"

- name: "Hashistack | Commons tasks | Get numbers of nodes in cluster"
  ansible.builtin.set_fact:
    group_item_count: "{{ groups['hashistack'] | length }}"
