  - name: "Hashistack | Firewall | Open ports for SSH & Web"
    community.general.ufw:
      rule: allow
      direction: in
      proto: "{{ item.proto }}"
      port: "{{ item.port }}"
    loop:
      - { proto: "tcp", port: "{{ ssh_port }}"}
      - { proto: "tcp", port: "80"}
      - { proto: "tcp", port: "443"}

  - name: "Hashistack | Firewall | Allow in and out on interface docker0"
    community.general.ufw:
      rule: allow
      interface: docker0
      direction: "{{ item }}"
    loop:
      - in
      - out

  - name: "Hashistack | Firewall | Allow in and out on interface nomad"
    community.general.ufw:
      rule: allow
      interface: nomad
      direction: "{{ item }}"
    loop:
      - in
      - out

  - name: "Hashistack | Firewall | General configuration UFW"
    community.general.ufw:
      state: enabled
      direction: "{{ item.direction }}"
      policy: "{{ item.policy }}"
    loop:
      - { direction: "outgoing", policy: "allow"}
      - { direction: "incoming", policy: "deny"}
