---
# defaults file for operate

# General
nomad_http_scheme: "https"
nomad_http_ip: "127.0.0.1"
nomad_http_port: 4646
nomad_job_files_dir: "/var/tmp/hashistack/nomad"
nomad_job_file: "{{ nomad_job_files_dir }}/{{ job_name }}.hcl"
nomad_job_name: "{{ fqdn }}"
nomad_conf_dir: "/etc/nomad.d"

nomad_operate_log_level: info
nomad_operate_prometheus_retention_time: "24h"

check_online_version: true

nomad_operate_dc_name: "dc1"

nomad_unsecure: false

nomad_version: 1.6.2

binary_path: "/usr/bin"
nomad_path: "{{ binary_path }}"

# TLS
nomad_operate_tls_ca_host: localhost
nomad_operate_tls_ca_host_dir: "{{ project_dir }}/env/host_vars/{{ inventory_hostname }}/tls"
nomad_operate_tls_ca_pubkey: "hashistack-ca.pem"
nomad_operate_tls_ca_privatekey: "hashistack-ca-key.pem"
nomad_operate_tls_ca_provider: "ownca"

nomad_operate_tls_host_certificate_dir: "/etc/ssl/hashistack"

nomad_operate_tls_cert: "{{ nomad_operate_dc_name }}-server-nomad.pem"
nomad_operate_tls_privatekey: "{{ nomad_operate_dc_name }}-server-nomad.key"

# Backup
nomad_backup_basename: "nomad_{{ inventory_hostname | replace('.', '_') }}_{{ ansible_date_time.date }}"

# Traefik
traefik_entrypoints: "https"
traefik_certresolver: "myresolver"
traefik_nomad_http_ip: "172.26.64.1"
traefik_nomad_basic_auth_user: "nomad"

# Notification from Ansible
notification: true
delivery_method: mail

# by Mail
mail_subject: "Ansible: {{ fqdn }}"
mail_msg: '<h3><a href="{{ fqdn }}">{{ fqdn }}</a></h3><br />Username: {{ traefik_nomad_basic_auth_user }}<br />Password: {{ traefik_nomad_basic_auth_password }}<br />'
mail_to: "{{ operator }}"

# by RocketChat
rocketchat_msg: "Ansible Tasks Deploy"
rocketchat_attachments: true
rocketchat_attachments_text: "Success!"
rocketchat_attachments_title: "Info"
rocketchat_attachments_collapsed: "false"
rocketchat_attachments_fields:
- { short: "true", title: "URL", value: "{{ fqdn }}" }
- { short: "true", title: "Username", value: "{{ traefik_nomad_basic_auth_user }}" }
- { short: "true", title: "Password", value: "{{ traefik_nomad_basic_auth_password }}" }

# by NTFY
ntfy_msg: |
  URL: {{ fqdn }}
  Username: {{ traefik_nomad_basic_auth_user }}
  Password: {{ traefik_nomad_basic_auth_password }}
